monolog:
    channels: [ 'deprecation' ]

    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            file_permission: "0666"
            level: notice
            channels: [ "!event", "!doctrine", '!deprecation' ]
            max_files: 14

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
