security:
    providers:
        memory_users:
            memory:
                users:
                    admin:
                        password: '%env(ADMIN_PASSWORD)%'
                        roles: 'ROLE_ADMIN'

    password_hashers:
        Symfony\Component\Security\Core\User\InMemoryUser: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: memory_users
            form_login:
                login_path: login
                check_path: login
                enable_csrf: true
                default_target_path: '/assessment/claim/create'

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_ADMIN }

