services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Web\Http\:
        resource: '%kernel.project_dir%/src/Web/Http/**/*.php'
        tags: [ 'controller.service_arguments' ]
